config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'courses#index'
  get 'courses/new', to: 'courses#new'
  get 'about', to: 'pages#about'
  resources :students, except: [:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
    validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
    validates :name, presence: true, length: { minimum: 5, maximum: 50 }
    validates :description, presence: true, length: { minimum: 10, maximum: 300 }
    has_many :student_courses
    has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { minimum: 5, maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: { with: VALID_EMAIL_REGEX }
    has_secure_password
    has_many :student_courses
    has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action :require_user
    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= Student.find(session[:student_id]) if session[:student_id]
    end

    def logged_in?
        !!current_user
    end

    def require_user
        unless logged_in?
            flash[:notice] = "You must be logged in to perform that action."
            redirect_to login_path
        end
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    skip_before_action :require_user
    
    def index
        @courses = Course.all
    end

    def new
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    
    def new
    end

    def create
        student = Student.find_by(email: params[:logins][:email].downcase)
        if student && student.authenticate(params[:logins][:password])
            session[:student_id] = student.id
            flash[:notice] = "You have successfully logged in."
            redirect_to student
        else
            flash.now[:notice] = "Something was wrong with your login information."
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        session[:student_id] = nil
        flash[:notice] = "You've successfully logged out."
        redirect_to root_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    skip_before_action :require_user
    
    def about
    end
end

app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
    def create
        course_to_add = Course.find(params[:course_id])
        unless current_user.courses.include?(course_to_add)
            StudentCourse.create(course: course_to_add, student: current_user)
            flash[:notice] = "You've successfully enrolled in #{course_to_add.name}."
            redirect_to current_user
        else
            flash[:notice] = "Something was wrong with your enrollment."
            redirect_to root_path
        end
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    skip_before_action :require_user, only: [:new, :create]
    before_action :set_student, only: [:show, :edit, :update]
    before_action :require_same_student, only: [:edit, :update]

    def index
        @students = Student.all
    end
    
    def show
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.new(student_params)
        if @student.save
            flash[:notice] = "You have successfully signed up."
            redirect_to @student
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
    end

    def update
        if @student.update(student_params)
            flash[:notice] = "You've successfully updated your profile."
            redirect_to @student
        else
            render :edit, status: :unprocessable_entity
        end
    end

    private

    def set_student
        @student = Student.find(params[:id])
    end
    
    def student_params
        params.require(:student).permit(:name, :email, :password, :password_confirmation)
    end

    def require_same_student
        if current_user != @student
            flash[:notice] = "You can only edit your own profile."
            redirect_to student_path(current_user)
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def session_link
        logged_in? ? link_to("Log out", logout_path, data: { turbo_method: :delete }) : link_to("Log in", login_path)
    end
end

app/views/courses/index.html.erb
<div class="row">
    <div class="col s12">
        <h3 class="center-align title-color">Course Listing</h3>
    </div>
</div>
<div class="row">
  <% @courses.each do |course| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.short_name %>: <%= course.name %></span>
          <p><%= course.description %></p>
        </div>
        <div class="card-action">
          <%= link_to "Enroll", course_enroll_path(course_id: course.id), data: { turbo_method: :post } if logged_in? && current_user.courses.exclude?(course) %>
          <a href="#">Info</a>
        </div>
      </div>
    </div>
  <% end %> 
</div>

app/views/courses/new.html.erb
<h1>This is the new course page</h1>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container center-align">
      © 2024 Tech University
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content fw-6">
    <li><%= link_to "Sign up", new_student_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Profile", student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><%= session_link %></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content fw-6">
    <li><%= link_to "Sign up", new_student_path %></li>
    <% if logged_in? %>
      <li><%= link_to "Profile", student_path(current_user) %></li>
    <% end %>
    <li class="divider"></li>
    <li><%= session_link %></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to "Tech University", root_path, class: "brand-logo right" %>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="left hide-on-med-and-down fw-6">
          <li><%= link_to "Courses", root_path %></li>
          <li><%= link_to "Students", students_path if logged_in? %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
        <ul class="sidenav fw-6" id="mobile-demo">
          <li><%= link_to "Courses", root_path %></li>
          <li><%= link_to "Students", students_path if logged_in? %></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navigation' %>    
    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
    <div class="row center sign-up-form">
        <div class="col s12 m12 l12">
            <div class="card-panel">
                <h3 class="header title-color">Log in!</h3>
                <div class="row">
                    <%= form_with(scope: :logins, url: login_path, class: "col s12") do |f| %>
                        <div class="row">
                            <div class="input-field col s12">
                            <i class="material-icons prefix">person</i>
                                <%= f.email_field :email, autofocus: true %>
                                <%= f.label :email %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                            <i class="material-icons prefix">lock</i>
                                <%= f.password_field :password %>
                                <%= f.label :password %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <%= f.button class: "btn teal lighten-2 waves-effect waves-light right fw-6" do %>
                                    Log in
                                    <i class="material-icons right">arrow_forward</i>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pages/about.html.erb
<h1>Hi this is the about page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="container">
        <div class="row sign-up-form">
            <div class="col s12 m12 l12">
                <div class="card-panel red lighten-2">
                    <span class="white-text">
                        <strong><%= pluralize(obj.errors.count, "error") %></strong> prohibited your profile from being created:
                        <ul>
                            <% obj.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </span>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
    <div class="row center sign-up-form">
        <div class="col s12 m12 l12">
            <div class="card-panel">
                <h3 class="header title-color"><%= @student.new_record? ? "Sign up!" : "Edit your profile" %></h3>
                <div class="row">
                    <%= form_with(model: @student, class: "col s12") do |f| %>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">person_add</i>
                                <%= f.text_field :name, autofocus: true, data: { length: 50 } %>
                                <%= f.label :name, class: "active" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">mail</i>
                                <%= f.email_field :email, data: { length: 105 } %>
                                <%= f.label :email, class: "active" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">lock_open</i>
                                <%= f.password_field :password %>
                                <%= f.label :password, class: "active" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <i class="material-icons prefix">lock_outline</i>
                                <%= f.password_field :password_confirmation %>
                                <%= f.label :password_confirmation, class: "active" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <% if @student.new_record? %>
                                    <%= f.button class: "btn teal lighten-2 waves-effect waves-light right" do %>
                                        Sign up
                                        <i class="material-icons right">fingerprint</i>
                                    <% end %>
                                <% else %>
                                    <%= f.button class: "btn teal lighten-2 waves-effect waves-light right" do %>
                                        Submit changes
                                        <i class="material-icons right">border_color</i>
                                    <% end %>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
    <div class="col s12">
        <h3 class="center-align title-color">Students Directory</h3>
    </div>
</div>
<div class="row">
  <% @students.each do |student| %>
    <div class="col s6 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Name: <%= student.name %></span>
          <p>Email: <%= student.email %></p>
          <p>Course Enrollments: None</p>
        </div>
        <div class="card-action">
          <%= link_to "View profile", student_path(student) %>
        </div>
      </div>
    </div>
  <% end %> 
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row sign-up-form">
    <div class="col s6 m6">
        <div class="card blue-grey darken-1">
            <div class="card-content white-text">
                <span class="card-title">Name: <%= @student.name %></span>
                <p>Email: <%= @student.email %></p>
                <p>Course Enrollments: 
                    <% if @student.courses.empty? %>
                        None
                    <% else %>
                        <ul>
                            <% @student.courses.each do |course| %>
                                <li>· <%= course.name %></li>
                            <% end %>
                        </ul>
                    <% end %>
                </p>
            </div>
            <% if current_user == @student %>
                <div class="card-action">
                    <%= link_to edit_student_path(@student) do %>
                        <i class="material-icons left">create</i>
                        Edit your profile
                    <% end %>
                </div>
            <% end %>
        </div>
        <!--<%= link_to edit_student_path(@student), class: "waves-effect waves-light btn" do %>
            <i class="material-icons left">create</i>
            Edit your profile
        <% end %>-->
    </div> 
</div>